### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by fjsmith181** [oshablue/dacqman#1]
When running dacqman it looked completely different from the demo video, maybe a more recent version than the release? Also there were several error displayed in the console. The other thing we noticed was that it would save the single waveform but wouldn't save the batch files. Below are screen shots from the console.

The first image is the error that was encountered on Mac OS X.
![Screen Shot 2020-05-18 at 1 51 29 PM](https://user-images.githubusercontent.com/60709728/82329150-e004ed80-99ae-11ea-8576-81b67fd53185.png)

Machine details
<img width="267" alt="Screen Shot 2020-05-19 at 9 00 17 AM" src="https://user-images.githubusercontent.com/60709728/82329340-2f4b1e00-99af-11ea-8767-9311c5bbe9b6.png">

The first image is the error that was encountered on Windows 10.
<img width="547" alt="Screen Shot 2020-05-18 at 2 40 57 PM" src="https://user-images.githubusercontent.com/60709728/82329221-f7dc7180-99ae-11ea-913c-1ff560c07408.png">

Machine details
![Screen Shot 2020-05-19 at 9 01 36 AM](https://user-images.githubusercontent.com/60709728/82329469-5dc8f900-99af-11ea-9aca-70c0e331a4dd.png)

Let me know if you have any questions. Thanks

**Comment by oshablue** [comment]
Thanks for posting this issue, much appreciated.  The details about the operating system and screenshots of errors also much appreciated.

I've split out this into 3 separate issues, #2, #3, and #4.  Two are presumed closed (feel free to update that if they don't address your concerns).  

In #4 I've indicated a request for more info to help on this.  I should be able to reply much more quickly, apologies on the delay in my responses.

Closing this issue to funnel work into the individual issues.

Thanks!

**Comment by oshablue** [comment]
Hi @fjsmith181,

A few further reminders, "just in case" -

(1) To run this release, the firmwares on the HDL board need to be updated.  Well, you may get away without it actually.  However, the best or most consistent channel scan behavior might come after updating the firmware.  A video for that probably be posted before you want to do this, so it might be best to just contact me directly when you're ready.  

There will be some information about updating firmwares in each of the corresponding [repositories,](https://github.com/oshablue?tab=repositories) or by digging around per usual channels in getting up and running with each code environment.  MPLABX-driven firmware updates you already know I think.  apio might be new.

(2) This point is probably moot now with the UI/UX setting switch indicated in #2, however, if you wanted to scan to batch file (raw format) and view those waveforms at the same time, you would use, in "regular" UI/UX interface (not data-capture focused interface), the corresponding "Continuous Channel Scan" button, or equivalent, and then expand the multiple waveform graph section, and perhaps close the single waveform graph section.  This is a good example and opportunity to look at the source, the control-port-buttons.json file, and perhaps explore the "Copy Custom Files to Local (or equivalent)" (via gear icon) option to customize this.  In that file, you'll see how the button is defined to do a multi-channel scan.  Again, this is quite different from the data-focused capture batch UI/UX that you're after here.  Nonetheless relevant to one particular aspect of the original ticket #1.

Thanks.
